name: kandy
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bottom_navy_bar: ^6.0.0
  cached_network_image: 
  carousel_pro: 
  carousel_slider: 
  cloud_firestore: 
 
  cupertino_icons: 
  custom_navigation_drawer: 
  platform_device_id: ^1.0.1
  dio: 
  expandable_card: 
  firebase_auth: ^3.3.4
  firebase_database: 
  firebase_messaging: 
  flick_video_player: 
  simple_connection_checker: ^0.2.1
  flutter:
    sdk: flutter
 
  folding_cell: 
  font_awesome_flutter: 
  html: 
  network_to_file_image: 
  path_provider: 
  provider: 
  url_launcher: 
  video_player: ^2.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/Netflix-logo.png
    - images/netflix_icon.png
    - images/launch_image.png
    - images/pro_pic.png
